version: "3.8"
services:
  server:
    build:
      context: ./server/.
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: /go/src/the-fearsome-five/server-docker -verbose -ssl-cert="server.crt" -ssl-key="server.key"

  client:
    build:
      context: ./client/.
      dockerfile: Dockerfile
    command: /go/src/the-fearsome-five/client-docker -verbose -delay=10 -server=https://server:8000 -reset